version: "3"

services: 
  my_nginx:
   build: ./nginx
   container_name: my_nginx
   ports: 
    - 9900:80
   volumes:
    - ./nginx/etc/nginx.conf:/etc/nginx/nginx.conf
  
  my_jenkins:
    build: ./jenkins
    container_name: my_jenkins
    privileged: true
    user: root
    ports:
      - 9901:8080
      - 50000:50000

    volumes:
      - ./jenkins/jenkins_home:/var/jenkins_home


  service_1:
    build: ./ubuntu
    container_name: service_1
    privileged: true
    ports:
      - 9988:9000
      - 3322:22
    user: root
    tty: true
    stdin_open: true
    volumes:
      - ./ubuntu/var/develop/script:/var/develop/td20/script
    
  
    






  
  
            

  
